export const STOP_KAMEHAMEHA = 'STOP_KAMEHAMEHA';
export const CHARGE_KAMEHAMEHA = 'CHARGE_KAMEHAMEHA';
export const FIRE_KAMEHAMEHA = 'FIRE_KAMEHAMEHA';

export const VEGETA_ATTACK = 'VEGETA_ATTACK';
export const STOP_VEGETA_ATTACK = 'STOP_VEGETA_ATTACK';
